[package]
name = "cosmwasm-crypto"
version = "1.5.0"
authors = ["Mauro Lacy <maurolacy@users.noreply.github.com>"]
edition = "2021"
description = "Crypto bindings for cosmwasm contracts"
repository = "https://github.com/CosmWasm/cosmwasm/tree/main/packages/crypto"
license = "Apache-2.0"

[features]
default = []

[lib]
# See https://bheisler.github.io/criterion.rs/book/faq.html#cargo-bench-gives-unrecognized-option-errors-for-valid-command-line-options
bench = false

[dependencies]
k256 = { version = "0.13.1", features = ["ecdsa"] }
ed25519-zebra = "3"
digest = "0.10"
rand_core = { version = "0.6", features = ["getrandom"] }
thiserror = "1.0.38"
# Not used directly, but needed to bump transitive dependency, see: https://github.com/CosmWasm/cosmwasm/pull/1899 for details.
ecdsa = "0.16.2"

[dev-dependencies]
criterion = "0.5.1"
serde = { version = "1.0.103", default-features = false, features = ["derive", "alloc"] }
serde_json = "1.0.40"
sha2 = "0.10"
hex = "0.4"
hex-literal = "0.3.1"
english-numbers = "0.3"

[[bench]]
name = "main"
harness = false
